### ISSUE TITLE
Dashboard Component

### ISSUE THREAD

**Issue by jaytula** [chingu-voyages/v8-bears-team-12#15]
Allows the user to find dining mates and will consist of two components: DiningMateSearch and DiningMateList.

Component might be better named `DiningMateDashboard`. 

There will be three functional UI Elements:

1. Input Text Field
2. Submit Button
3. My location Button

When either button is clicked, we expect to obtain a `locationToSearch` that has properties `latitude` and `longitude`

```js
const locationToSearch = {
  latitude: 37.23423,
  longitude: 83.44325,
};
```

`locationToSearch`  will be used to match with other users' restaurant preferences:  `restaurantsList`

Presuming a single user looks something like this:

```js

const exampleUser = {
  _id: '1234123412344',
  name: 'John Doe',
  email: 'johndoe@example.org',
  password: '0123456789abcdef',
  zipcode: '90210',
  interests: ['Video Games', 'Music'],
  dietRestrictions: 'gluten-free',
  restaurantsList: [
     {
        name: 'The Kimbap',
        address: `400 S Western Ave Ste 102, Los Angeles, CA 90020`,
        latitude: 34.0668582,
        longitude: -118.3095692
     }
  ]
}
```

In order to do a search, we'll have to go through each user's `restaurantsList` property and return the user if one or more  restaurants in the `restaurantsList` is below a certain distance threshold from the `locationToSearch`.

The returned result may be look like this:

```js
const matchedUsers = [
  {
    _id: '123142543abcdfef',
    restaurantsMatched: [
      {
        name: 'The Kimbap',
        address: `400 S Western Ave Ste 102, Los Angeles, CA 90020`,
        latitude: 34.0668582,
        longitude: -118.3095692
      }
    ]
  }
]
```

**Comment by gitasong** [comment]
Is this issue complete? If not, what still needs to be done?

**Comment by jaytula** [comment]
The functionality for finding dining mates has not been implemented.

**Comment by gitasong** [comment]
Are you still working on it, @jaytula ? If not, I might want to pick this one up whenever it's time to implement the matching feature.

**Comment by jaytula** [comment]
Issue stale. Closing
