### ISSUE TITLE
Profile Component

### ISSUE THREAD

**Issue by jaytula** [chingu-voyages/v8-bears-team-12#19]
Will be displayed for the route path '/path'.  It will have a form consisting of fields: name, email, password, zipcode, interests, dietRestrictions (dropdown menu: none, vegan, vegetarian, gluten-free).  And a Save Profile button

**Comment by janeslee** [comment]
done and merged

**Comment by janeslee** [comment]
Re-opened to refactor. WIP

**Comment by janeslee** [comment]
Basic functionality in place.

- Missing api endpoint to connect w/ DB
- Missing avatar functionality
- Needs testing with Jest
